inherit_from:
  - https://raw.githubusercontent.com/rails/rails/5-1-stable/.rubocop.yml

AllCops:
  Exclude:
    - lib/generators/**/templates/**/*
    - remove_data_attributes.gemspec
    - spec/dummy/**/*
    - tmp/**/*

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: normal
