language: ruby
sudo: false
rvm:
  - 2.3.5
  - 2.4.2
gemfile:
  - gemfiles/rails_40x.gemfile
  - gemfiles/rails_41x.gemfile
  - gemfiles/rails_42x.gemfile
  - gemfiles/rails_50x.gemfile
  - gemfiles/rails_51x.gemfile
matrix:
  exclude:
    - rvm: 2.4.2
      gemfile: gemfiles/rails_40x.gemfile
    - rvm: 2.4.2
      gemfile: gemfiles/rails_41x.gemfile
branches:
  only:
    - master
before_install:
  - gem update --system --no-doc
  - gem install bundler
